In [1]:
import cv2
import numpy as np


In [2]:
#读入图片：默认彩色图，cv2.IMREAD_GRAYSCALE灰度图，cv2.IMREAD_UNCHANGED包含alpha通道
img = cv2.imread('1.jpg')
cv2.imshow('src',img)
print(img.shape) # (h,w,c)
print(img.size)
print(img.dtype)
print(img)
cv2.waitKey()

(384, 683, 3)
786816
uint8
[[[ 71  32  30]
  [ 71  32  30]
  [ 71  32  30]
  ..., 
  [ 71  33  31]
  [ 69  34  31]
  [ 69  34  31]]

 [[ 72  33  31]
  [ 72  33  31]
  [ 71  32  30]
  ..., 
  [ 71  33  31]
  [ 69  34  31]
  [ 69  34  31]]

 [[ 71  32  30]
  [ 71  32  30]
  [ 71  32  30]
  ..., 
  [ 71  33  31]
  [ 69  34  31]
  [ 69  34  31]]

 ..., 
 [[172 147 107]
  [228 204 162]
  [232 210 168]
  ..., 
  [ 85  47  29]
  [100  60  42]
  [ 93  53  35]]

 [[215 192 146]
  [231 208 162]
  [240 217 171]
  ..., 
  [ 93  55  43]
  [ 80  38  31]
  [ 92  50  43]]

 [[224 203 152]
  [239 218 167]
  [235 213 165]
  ..., 
  [ 81  43  38]
  [ 79  39  40]
  [ 86  46  47]]]


-1

In [3]:
#gray = cv2.imread('1.jpg',cv2.IMREAD_GRAYSCALE) #灰度图
#cv2.imshow('gray',gray)
#也可以这么写，先读入彩色图，再转灰度图
src = cv2.imread('1.jpg')
gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)
cv2.imshow('gray',gray)
print(gray.shape)
print(gray.size)
print(gray)
cv2.waitKey()

(384, 683)
262272
[[ 36  36  36 ...,  37  37  37]
 [ 37  37  36 ...,  37  37  37]
 [ 36  36  36 ...,  37  37  37]
 ..., 
 [138 194 200 ...,  46  59  52]
 [181 197 206 ...,  56  41  53]
 [190 205 201 ...,  46  44  51]]


-1

In [4]:
#注意，计算图片路径是错的，Opencv也不会提醒你，但print img时得到的结果是None
img2 = cv2.imread('2.jpg')
print(img2)

None


In [5]:
#如何解决“读到的图片不存在的问题”？ #加入判断语句，如果为空，做异常处理
img2 = cv2.imread('2.jpg')
if img2 == None:
    print('fail to load image!')

fail to load image!


In [6]:
#注意到，opencv读入的图片的彩色图是一个channel last的三维矩阵（h,w,c），即（高度，宽度，通道）
#有时候在深度学习中用到的的图片矩阵形式可能是channel first，那我们可以这样转一下
print(img.shape)
img = img.transpose(2,0,1)
print(img.shape)

(384, 683, 3)
(3, 384, 683)


In [7]:
#有时候还要扩展维度，比如要在要加一列做图片的个数，可以这么做
img = np.expand_dims(img, axis=0)
print(img.shape)

(1, 3, 384, 683)


In [8]:
#因为opencv读入的图片矩阵数值是0到255，有时我们需要对其进行归一化为0~1
img3 = cv2.imread('1.jpg')
img3 = img3.astype("float") / 255.0  #注意需要先转化数据类型为float
print(img3.dtype)
print(img3)



float64
[[[ 0.27843137  0.1254902   0.11764706]
  [ 0.27843137  0.1254902   0.11764706]
  [ 0.27843137  0.1254902   0.11764706]
  ..., 
  [ 0.27843137  0.12941176  0.12156863]
  [ 0.27058824  0.13333333  0.12156863]
  [ 0.27058824  0.13333333  0.12156863]]

 [[ 0.28235294  0.12941176  0.12156863]
  [ 0.28235294  0.12941176  0.12156863]
  [ 0.27843137  0.1254902   0.11764706]
  ..., 
  [ 0.27843137  0.12941176  0.12156863]
  [ 0.27058824  0.13333333  0.12156863]
  [ 0.27058824  0.13333333  0.12156863]]

 [[ 0.27843137  0.1254902   0.11764706]
  [ 0.27843137  0.1254902   0.11764706]
  [ 0.27843137  0.1254902   0.11764706]
  ..., 
  [ 0.27843137  0.12941176  0.12156863]
  [ 0.27058824  0.13333333  0.12156863]
  [ 0.27058824  0.13333333  0.12156863]]

 ..., 
 [[ 0.6745098   0.57647059  0.41960784]
  [ 0.89411765  0.8         0.63529412]
  [ 0.90980392  0.82352941  0.65882353]
  ..., 
  [ 0.33333333  0.18431373  0.11372549]
  [ 0.39215686  0.23529412  0.16470588]
  [ 0.36470588  0.20784314 

In [9]:
#存储图片
cv2.imwrite('test1.jpg',img3) #得到的是全黑的图片，因为我们把它归一化了
#所以要得到可视化的图，需要先*255还原
img3 = img3 * 255
cv2.imwrite('test2.jpg',img3)  #这样就可以看到彩色原图了

True

In [10]:
#opencv读入的矩阵是BGR，如果想转为RGB，可以这么转
img4 = cv2.imread('1.jpg')
img4 = cv2.cvtColor(img4,cv2.COLOR_BGR2RGB)

In [11]:
#访问像素
print(img4[10,10])  #3channels
print(gray[10,10]) #1channel
img4[10,10] = [255,255,255]
gray[10,10] = 255
print(img4[10,10])  #3channels
print(gray[10,10]) #1channel

[20 19 59]
24
[255 255 255]
255


In [12]:
#roi操作
roi = img4[200:550,100:450,:]
cv2.imshow('roi',roi)
cv2.waitKey()

-1

In [13]:
#分离通道
img5 = cv2.imread('1.jpg')
b,g,r = cv2.split(img5)
#合并通道
img5 = cv2.merge((b,g,r))
#也可以不拆分
img5[:,:,2] = 0  #将红色通道值全部设0