In [1]:
from PIL import Image
import numpy as np

In [2]:
img = Image.open('1.jpg')
print(img.format) 
print(img.size) #注意，省略了通道 (w，h)
print(img.mode)  #L为灰度图，RGB为真彩色,RGBA为加了透明通道


JPEG
(683, 384)
RGB


In [4]:
img.show()

In [4]:
#读取不到图片会抛出异常IOError，我们可以捕捉它，做异常处理
try:
    img2 = Image.open('2.jpg')
except IOError:
    print('fail to load image!')

fail to load image!


In [5]:
img.save('1.png')

In [6]:
#分离合并通道
r, g, b = img.split()
img = Image.merge("RGB", (b, g, r))

In [7]:
img = img.copy() #复制图像

In [8]:
img3 = Image.open('1.jpg')
roi = img3.crop((0,0,300,300)) #(左上x，左上y，右下x，右下y)坐标
roi.show()

In [5]:
gray = Image.open('1.jpg').convert('L')
gray.show()

In [12]:
#pillow读进来的图片不是矩阵，我们将图片转矩阵,channel last
arr = np.array(img3)
print(arr.shape)
print(arr.dtype)
print(arr)

(384, 683, 3)
uint8
[[[ 30  32  71]
  [ 30  32  71]
  [ 30  32  71]
  ..., 
  [ 31  33  71]
  [ 31  34  69]
  [ 31  34  69]]

 [[ 31  33  72]
  [ 31  33  72]
  [ 30  32  71]
  ..., 
  [ 31  33  71]
  [ 31  34  69]
  [ 31  34  69]]

 [[ 30  32  71]
  [ 30  32  71]
  [ 30  32  71]
  ..., 
  [ 31  33  71]
  [ 31  34  69]
  [ 31  34  69]]

 ..., 
 [[107 147 172]
  [162 204 228]
  [168 210 232]
  ..., 
  [ 29  47  85]
  [ 42  60 100]
  [ 35  53  93]]

 [[146 192 215]
  [162 208 231]
  [171 217 240]
  ..., 
  [ 43  55  93]
  [ 31  38  80]
  [ 43  50  92]]

 [[152 203 224]
  [167 218 239]
  [165 213 235]
  ..., 
  [ 38  43  81]
  [ 40  39  79]
  [ 47  46  86]]]


In [13]:
#矩阵再转为图像
new_im = Image.fromarray(arr)
new_im.save('3.png')

In [6]:
arr_gray = np.array(gray)
print(arr_gray.shape)
print(arr_gray.dtype)
print(arr_gray)

(384, 683)
uint8
[[ 35  35  35 ...,  36  37  37]
 [ 36  36  35 ...,  36  37  37]
 [ 35  35  35 ...,  36  37  37]
 ..., 
 [137 194 199 ...,  45  59  52]
 [180 196 205 ...,  55  40  52]
 [190 205 201 ...,  45  43  50]]
